name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
      
      - name: Lint with flake8
        run: |
          flake8 modules --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 modules --count --max-complexity=10 --max-line-length=127 --statistics
      
      - name: Run unit tests with Nose
        run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=modules
